<?php 
  function bbi2020_cptui_register_my_cpts() {

    /**
     * Post Type: Articles.
     */
  
    $labels = [
      "name" => __( "Articles", "bbi2020" ),
      "singular_name" => __( "Article", "bbi2020" ),
    ];
  
    $args = [
      "label" => __( "Articles", "bbi2020" ),
      "labels" => $labels,
      "description" => "",
      "public" => true,
      "publicly_queryable" => true,
      "show_ui" => true,
      "show_in_rest" => true,
      "rest_base" => "",
      "rest_controller_class" => "WP_REST_Posts_Controller",
      "has_archive" => true,
      "show_in_menu" => true,
      "show_in_nav_menus" => true,
      "delete_with_user" => false,
      "exclude_from_search" => false,
      "capability_type" => "post",
      "map_meta_cap" => true,
      "hierarchical" => false,
      "rewrite" => [ "slug" => "article", "with_front" => true ],
      "query_var" => true,
      "menu_icon" => "dashicons-text",
      "supports" => [ "title", "editor", "thumbnail", "revisions" ],
      "taxonomies" => [ "kind", "brand" ],
    ];
  
    register_post_type( "article", $args );
  
    /**
     * Post Type: Jobs.
     */
  
    $labels = [
      "name" => __( "Jobs", "bbi2020" ),
      "singular_name" => __( "Job", "bbi2020" ),
    ];
  
    $args = [
      "label" => __( "Jobs", "bbi2020" ),
      "labels" => $labels,
      "description" => "",
      "public" => true,
      "publicly_queryable" => true,
      "show_ui" => true,
      "show_in_rest" => true,
      "rest_base" => "",
      "rest_controller_class" => "WP_REST_Posts_Controller",
      "has_archive" => true,
      "show_in_menu" => true,
      "show_in_nav_menus" => true,
      "delete_with_user" => false,
      "exclude_from_search" => false,
      "capability_type" => "post",
      "map_meta_cap" => true,
      "hierarchical" => false,
      "rewrite" => [ "slug" => "job", "with_front" => true ],
      "query_var" => true,
      "menu_icon" => "dashicons-building",
      "supports" => [ "title", "editor", "thumbnail" ],
    ];
  
    register_post_type( "job", $args );
  }
  
  add_action( 'init', 'bbi2020_cptui_register_my_cpts' );

  function bbi2020_cptui_register_my_taxes() {

    /**
     * Taxonomy: Types.
     */
  
    $labels = [
      "name" => __( "Types", "bbi2020" ),
      "singular_name" => __( "Type", "bbi2020" ),
    ];
  
    $args = [
      "label" => __( "Types", "bbi2020" ),
      "labels" => $labels,
      "public" => true,
      "publicly_queryable" => true,
      "hierarchical" => false,
      "show_ui" => true,
      "show_in_menu" => true,
      "show_in_nav_menus" => true,
      "query_var" => true,
      "rewrite" => [ 'slug' => 'kind', 'with_front' => true, ],
      "show_admin_column" => false,
      "show_in_rest" => true,
      "rest_base" => "kind",
      "rest_controller_class" => "WP_REST_Terms_Controller",
      "show_in_quick_edit" => false,
      ];
    register_taxonomy( "kind", [ "post" ], $args );
  
    /**
     * Taxonomy: Brands.
     */
  
    $labels = [
      "name" => __( "Brands", "bbi2020" ),
      "singular_name" => __( "Brand", "bbi2020" ),
    ];
  
    $args = [
      "label" => __( "Brands", "bbi2020" ),
      "labels" => $labels,
      "public" => true,
      "publicly_queryable" => true,
      "hierarchical" => false,
      "show_ui" => true,
      "show_in_menu" => true,
      "show_in_nav_menus" => true,
      "query_var" => true,
      "rewrite" => [ 'slug' => 'brand', 'with_front' => true, ],
      "show_admin_column" => false,
      "show_in_rest" => true,
      "rest_base" => "brand",
      "rest_controller_class" => "WP_REST_Terms_Controller",
      "show_in_quick_edit" => false,
      ];
    register_taxonomy( "brand", [ "post" ], $args );
  }
 
  add_action( 'init', 'bbi2020_cptui_register_my_taxes' );
  
  if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
      'key' => 'group_5e1f8d1b19bab',
      'title' => 'Article',
      'fields' => array(
        array(
          'key' => 'field_5e1f8eedfdebd',
          'label' => 'Format',
          'name' => 'article-format',
          'type' => 'radio',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array(
            'link' => 'Link',
            'pdf' => 'PDF',
          ),
          'allow_null' => 0,
          'other_choice' => 0,
          'default_value' => 'link',
          'layout' => 'horizontal',
          'return_format' => 'value',
          'save_other_choice' => 0,
        ),
        array(
          'key' => 'field_5e20b6103cf61',
          'label' => 'Publication name',
          'name' => 'publication-name',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5e20b6d3d55fa',
          'label' => 'Publication date',
          'name' => 'publication-date',
          'type' => 'date_picker',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'display_format' => 'F j, Y',
          'return_format' => 'Ymd',
          'first_day' => 0,
        ),
        array(
          'key' => 'field_5e1f8ecafdebc',
          'label' => 'Short description',
          'name' => 'description',
          'type' => 'textarea',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'maxlength' => '',
          'rows' => '',
          'new_lines' => 'wpautop',
        ),
        array(
          'key' => 'field_5e1f928dbbb10',
          'label' => 'Image',
          'name' => 'image',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'array',
          'preview_size' => 'medium',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array(
          'key' => 'field_5e1f8f3afdebe',
          'label' => 'Body',
          'name' => 'body',
          'type' => 'wysiwyg',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5e1f8eedfdebd',
                'operator' => '==',
                'value' => 'page',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'tabs' => 'all',
          'toolbar' => 'full',
          'media_upload' => 1,
          'delay' => 0,
        ),
        array(
          'key' => 'field_5e1f8fc1fdebf',
          'label' => 'URL',
          'name' => 'url',
          'type' => 'url',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5e1f8eedfdebd',
                'operator' => '==',
                'value' => 'link',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
        ),
        array(
          'key' => 'field_5e1f8fd5fdec0',
          'label' => 'PDF',
          'name' => 'pdf',
          'type' => 'file',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5e1f8eedfdebd',
                'operator' => '==',
                'value' => 'pdf',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'url',
          'library' => 'all',
          'min_size' => '',
          'max_size' => '',
          'mime_types' => 'pdf',
        ),
        array(
          'key' => 'field_5e1f90c700872',
          'label' => 'Type',
          'name' => 'article-type',
          'type' => 'taxonomy',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '50',
            'class' => '',
            'id' => '',
          ),
          'taxonomy' => 'kind',
          'field_type' => 'radio',
          'allow_null' => 0,
          'add_term' => 1,
          'save_terms' => 1,
          'load_terms' => 1,
          'return_format' => 'object',
          'multiple' => 0,
        ),
        array(
          'key' => 'field_5e1f912036429',
          'label' => 'Brands',
          'name' => 'article-brands',
          'type' => 'taxonomy',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '50',
            'class' => '',
            'id' => '',
          ),
          'taxonomy' => 'brand',
          'field_type' => 'checkbox',
          'add_term' => 1,
          'save_terms' => 1,
          'load_terms' => 1,
          'return_format' => 'object',
          'multiple' => 0,
          'allow_null' => 0,
        ),
      ),
      'location' => array(
        array(
          array(
            'param' => 'post_type',
            'operator' => '==',
            'value' => 'article',
          ),
        ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => array(
        0 => 'the_content',
        1 => 'format',
        2 => 'page_attributes',
        3 => 'featured_image',
        4 => 'categories',
        5 => 'tags',
      ),
      'active' => true,
      'description' => '',
    ));
    
    acf_add_local_field_group(array(
      'key' => 'group_5e1cb6182aa15',
      'title' => 'Custom Page',
      'fields' => array(
        array(
          'key' => 'field_5e1e0a4a543b9',
          'label' => 'Has Hero',
          'name' => 'has_hero',
          'type' => 'true_false',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'message' => '',
          'default_value' => 0,
          'ui' => 1,
          'ui_on_text' => '',
          'ui_off_text' => '',
        ),
        array(
          'key' => 'field_5e1e0a88543bb',
          'label' => 'Hero',
          'name' => 'hero',
          'type' => 'group',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5e1e0a4a543b9',
                'operator' => '==',
                'value' => '1',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'layout' => 'block',
          'sub_fields' => array(
            array(
              'key' => 'field_5e1e0a9d543bc',
              'label' => 'Desktop image',
              'name' => 'desktop_image',
              'type' => 'image',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
              ),
              'return_format' => 'array',
              'preview_size' => 'medium',
              'library' => 'all',
              'min_width' => '',
              'min_height' => '',
              'min_size' => '',
              'max_width' => '',
              'max_height' => '',
              'max_size' => '',
              'mime_types' => '',
            ),
            array(
              'key' => 'field_5e1e0ab2543bd',
              'label' => 'Mobile image',
              'name' => 'mobile_image',
              'type' => 'image',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
              ),
              'return_format' => 'array',
              'preview_size' => 'medium',
              'library' => 'all',
              'min_width' => '',
              'min_height' => '',
              'min_size' => '',
              'max_width' => '',
              'max_height' => '',
              'max_size' => '',
              'mime_types' => '',
            ),
            array(
              'key' => 'field_5e20899daa785',
              'label' => 'Use animated title',
              'name' => 'use_animated_title',
              'type' => 'true_false',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'message' => '',
              'default_value' => 0,
              'ui' => 1,
              'ui_on_text' => '',
              'ui_off_text' => '',
            ),
            array(
              'key' => 'field_5e2089caaa786',
              'label' => 'Animated title',
              'name' => 'animated_title',
              'type' => 'group',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array(
                array(
                  array(
                    'field' => 'field_5e20899daa785',
                    'operator' => '==',
                    'value' => '1',
                  ),
                ),
              ),
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'layout' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5e208a58aa787',
                  'label' => 'Static title before',
                  'name' => 'static-pre',
                  'type' => 'text',
                  'instructions' => 'Appears above the animated words on a separate line',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                ),
                array(
                  'key' => 'field_5e20926eaa788',
                  'label' => 'Animated words',
                  'name' => 'animated',
                  'type' => 'textarea',
                  'instructions' => 'Animated words/phrases need to be separated by a line break. You can have as many lines as you want and the animation will cycle through each word/phrase and stop at the end.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => 4,
                  'new_lines' => '',
                ),
                array(
                  'key' => 'field_5e2092e3aa789',
                  'label' => 'Static title after',
                  'name' => 'static-post',
                  'type' => 'text',
                  'instructions' => 'Appears below the animated words on a separate line',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                ),
                array(
                  'key' => 'field_5e20936eaa78a',
                  'label' => 'Repeats',
                  'name' => 'repeats',
                  'type' => 'number',
                  'instructions' => '-1 for forever
    0 for none',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => 0,
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'min' => -1,
                  'max' => 100,
                  'step' => 1,
                ),
                array(
                  'key' => 'field_5e20afff37d9c',
                  'label' => 'Fade in body',
                  'name' => 'fade_in_body',
                  'type' => 'true_false',
                  'instructions' => 'Fades body text in after title',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'message' => '',
                  'default_value' => 1,
                  'ui' => 1,
                  'ui_on_text' => '',
                  'ui_off_text' => '',
                ),
              ),
            ),
            array(
              'key' => 'field_5e1e0ab9543be',
              'label' => 'Title',
              'name' => 'title',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array(
                array(
                  array(
                    'field' => 'field_5e20899daa785',
                    'operator' => '!=',
                    'value' => '1',
                  ),
                ),
              ),
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array(
              'key' => 'field_5e1e0abf543bf',
              'label' => 'Body',
              'name' => 'body',
              'type' => 'textarea',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'maxlength' => '',
              'rows' => '',
              'new_lines' => '',
            ),
            array(
              'key' => 'field_5e1e2c2a0a5a8',
              'label' => 'Desktop text style',
              'name' => 'text_style_desktop',
              'type' => 'radio',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array(
                'black' => 'Black',
                'white' => 'White',
                'white-overlay' => 'White with fade',
                'black-overlay' => 'Black with fade',
              ),
              'allow_null' => 0,
              'other_choice' => 0,
              'default_value' => 'black',
              'layout' => 'horizontal',
              'return_format' => 'value',
              'save_other_choice' => 0,
            ),
            array(
              'key' => 'field_5e1e2cc10a5a9',
              'label' => 'Mobile text style',
              'name' => 'text_style_mobile',
              'type' => 'radio',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array(
                'black' => 'Black',
                'white' => 'White',
                'white-overlay' => 'White with fade',
                'black-overlay' => 'Black with fade',
              ),
              'allow_null' => 0,
              'other_choice' => 0,
              'default_value' => 'black',
              'layout' => 'horizontal',
              'return_format' => 'value',
              'save_other_choice' => 0,
            ),
            array(
              'key' => 'field_5e1e341875914',
              'label' => 'Desktop fade color',
              'name' => 'fade_color_desktop',
              'type' => 'color_picker',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array(
                array(
                  array(
                    'field' => 'field_5e1e2c2a0a5a8',
                    'operator' => '==',
                    'value' => 'white-overlay',
                  ),
                ),
                array(
                  array(
                    'field' => 'field_5e1e2c2a0a5a8',
                    'operator' => '==',
                    'value' => 'black-overlay',
                  ),
                ),
              ),
              'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
            ),
            array(
              'key' => 'field_5e1e343d75915',
              'label' => 'Mobile fade color',
              'name' => 'fade_color_mobile',
              'type' => 'color_picker',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array(
                array(
                  array(
                    'field' => 'field_5e1e2cc10a5a9',
                    'operator' => '==',
                    'value' => 'white-overlay',
                  ),
                ),
                array(
                  array(
                    'field' => 'field_5e1e2cc10a5a9',
                    'operator' => '==',
                    'value' => 'black-overlay',
                  ),
                ),
              ),
              'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
            ),
            array(
              'key' => 'field_5e1f555b671af',
              'label' => 'Desktop scale point',
              'name' => 'scale_point_desktop',
              'type' => 'select',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
              ),
              'choices' => array(
                'center center' => 'Center',
                'center top' => 'Top center',
                'center bottom' => 'Bottom center',
                'top left' => 'Top left',
                'top right' => 'Top right',
                'center left' => 'Center left',
                'center right' => 'Center right',
                'bottom left' => 'Bottom left',
                'bottom right' => 'Bottom right',
              ),
              'default_value' => array(
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'return_format' => 'value',
              'ajax' => 0,
              'placeholder' => '',
            ),
            array(
              'key' => 'field_5e1f5495671ae',
              'label' => 'Mobile scale point',
              'name' => 'scale_point_mobile',
              'type' => 'select',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
              ),
              'choices' => array(
                'center center' => 'Center',
                'center top' => 'Top center',
                'center bottom' => 'Bottom center',
                'top left' => 'Top left',
                'top right' => 'Top right',
                'center left' => 'Center left',
                'center right' => 'Center right',
                'bottom left' => 'Bottom left',
                'bottom right' => 'Bottom right',
              ),
              'default_value' => array(
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'return_format' => 'value',
              'ajax' => 0,
              'placeholder' => '',
            ),
          ),
        ),
        array(
          'key' => 'field_5e1cb9501288f',
          'label' => 'Sections',
          'name' => 'sections',
          'type' => 'flexible_content',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'layouts' => array(
            'layout_5e29d03d9aae8' => array(
              'key' => 'layout_5e29d03d9aae8',
              'name' => 'plain-text',
              'label' => 'Plain text',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5e29d03d9aaed',
                  'label' => 'Title',
                  'name' => 'section-title',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                ),
                array(
                  'key' => 'field_5e29d03d9aaee',
                  'label' => 'Body',
                  'name' => 'section-body',
                  'type' => 'wysiwyg',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'tabs' => 'all',
                  'toolbar' => 'basic',
                  'media_upload' => 0,
                  'delay' => 0,
                ),
                array(
                  'key' => 'field_5e29d27af5ff8',
                  'label' => 'Max columns',
                  'name' => 'max-columns',
                  'type' => 'radio',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    2 => '2',
                    3 => '3',
                    4 => '4',
                  ),
                  'allow_null' => 0,
                  'other_choice' => 0,
                  'default_value' => 4,
                  'layout' => 'horizontal',
                  'return_format' => 'value',
                  'save_other_choice' => 0,
                ),
                array(
                  'key' => 'field_5e29d3aa6c9e5',
                  'label' => 'Vertical alignment',
                  'name' => 'valign',
                  'type' => 'radio',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    'top' => 'Top',
                    'center' => 'Center',
                    'bottom' => 'Bottom',
                  ),
                  'allow_null' => 0,
                  'other_choice' => 0,
                  'default_value' => 'center',
                  'layout' => 'horizontal',
                  'return_format' => 'value',
                  'save_other_choice' => 0,
                ),
                array(
                  'key' => 'field_5e29d03d9aaf0',
                  'label' => 'Enabled',
                  'name' => 'section-enabled',
                  'type' => 'true_false',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'message' => '',
                  'default_value' => 1,
                  'ui' => 1,
                  'ui_on_text' => 'On',
                  'ui_off_text' => 'Off',
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            'layout_5e1cb955e2ff4' => array(
              'key' => 'layout_5e1cb955e2ff4',
              'name' => 'image-across-columns',
              'label' => 'Image Across Columns',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5e1cb97d12890',
                  'label' => 'Image',
                  'name' => 'image',
                  'type' => 'image',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'return_format' => 'array',
                  'preview_size' => 'large',
                  'library' => 'all',
                  'min_width' => '',
                  'min_height' => '',
                  'min_size' => '',
                  'max_width' => '',
                  'max_height' => '',
                  'max_size' => '',
                  'mime_types' => '',
                ),
                array(
                  'key' => 'field_5e1cbadf12891',
                  'label' => 'Image Columns',
                  'name' => 'image-columns',
                  'type' => 'radio',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '33.33',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    1 => '1',
                    2 => '2',
                    3 => '3',
                    4 => '4',
                  ),
                  'allow_null' => 0,
                  'other_choice' => 0,
                  'default_value' => 3,
                  'layout' => 'vertical',
                  'return_format' => 'value',
                  'save_other_choice' => 0,
                ),
                array(
                  'key' => 'field_5e1cbba012895',
                  'label' => 'Image position',
                  'name' => 'image-position',
                  'type' => 'radio',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '33.33',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    'left' => 'Left',
                    'right' => 'Right',
                  ),
                  'allow_null' => 0,
                  'other_choice' => 0,
                  'default_value' => 'left',
                  'layout' => 'vertical',
                  'return_format' => 'value',
                  'save_other_choice' => 0,
                ),
                array(
                  'key' => 'field_5e1cbbd112896',
                  'label' => 'Image fill',
                  'name' => 'image-fill',
                  'type' => 'radio',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '33.33',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    'normal' => 'Normal',
                    'padded' => 'Padding',
                  ),
                  'allow_null' => 0,
                  'other_choice' => 0,
                  'default_value' => '',
                  'layout' => 'vertical',
                  'return_format' => 'value',
                  'save_other_choice' => 0,
                ),
                array(
                  'key' => 'field_5e1cbb0312892',
                  'label' => 'Title',
                  'name' => 'image-title',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                ),
                array(
                  'key' => 'field_5e1cbb2112893',
                  'label' => 'Body',
                  'name' => 'image-body',
                  'type' => 'wysiwyg',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'tabs' => 'all',
                  'toolbar' => 'basic',
                  'media_upload' => 0,
                  'delay' => 0,
                ),
                array(
                  'key' => 'field_5e1cbb5212894',
                  'label' => 'Text Vertical Alignment',
                  'name' => 'text-valign',
                  'type' => 'radio',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    'flex-start' => 'Top',
                    'center' => 'Middle',
                    'flex-end' => 'Bottom',
                  ),
                  'allow_null' => 0,
                  'other_choice' => 0,
                  'default_value' => '',
                  'layout' => 'horizontal',
                  'return_format' => 'value',
                  'save_other_choice' => 0,
                ),
                array(
                  'key' => 'field_5e1cfb22cc898',
                  'label' => 'Enabled',
                  'name' => 'section-enabled',
                  'type' => 'true_false',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'message' => '',
                  'default_value' => 1,
                  'ui' => 1,
                  'ui_on_text' => 'On',
                  'ui_off_text' => 'Off',
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            'layout_5e1cdaaa88a7a' => array(
              'key' => 'layout_5e1cdaaa88a7a',
              'name' => 'locations',
              'label' => 'Locations',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5e1ce0f588a7b',
                  'label' => 'Section title',
                  'name' => 'section-title',
                  'type' => 'text',
                  'instructions' => 'Appears in the first location box',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                ),
                array(
                  'key' => 'field_5e29d9d6f1996',
                  'label' => 'Section body',
                  'name' => 'section-body',
                  'type' => 'textarea',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => 4,
                  'new_lines' => 'wpautop',
                ),
                array(
                  'key' => 'field_5e28e35ba8066',
                  'label' => 'Max columns',
                  'name' => 'max-columns',
                  'type' => 'radio',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    2 => '2',
                    3 => '3',
                    4 => '4',
                  ),
                  'allow_null' => 0,
                  'other_choice' => 0,
                  'default_value' => 4,
                  'layout' => 'horizontal',
                  'return_format' => 'value',
                  'save_other_choice' => 0,
                ),
                array(
                  'key' => 'field_5e1ce12888a7c',
                  'label' => 'Locations',
                  'name' => 'location-items',
                  'type' => 'repeater',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'collapsed' => '',
                  'min' => 0,
                  'max' => 0,
                  'layout' => 'table',
                  'button_label' => 'Add Location',
                  'sub_fields' => array(
                    array(
                      'key' => 'field_5e1ce14288a7d',
                      'label' => 'Title',
                      'name' => 'location-title',
                      'type' => 'text',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                    ),
                    array(
                      'key' => 'field_5e1ce14e88a7e',
                      'label' => 'Image',
                      'name' => 'image',
                      'type' => 'image',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'return_format' => 'array',
                      'preview_size' => 'medium',
                      'library' => 'all',
                      'min_width' => '',
                      'min_height' => '',
                      'min_size' => '',
                      'max_width' => '',
                      'max_height' => '',
                      'max_size' => '',
                      'mime_types' => '',
                    ),
                    array(
                      'key' => 'field_5e1ce19f88a7f',
                      'label' => 'Description',
                      'name' => 'location-description',
                      'type' => 'textarea',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'maxlength' => '',
                      'rows' => 4,
                      'new_lines' => 'wpautop',
                    ),
                    array(
                      'key' => 'field_5e29f1a47ce2a',
                      'label' => 'Link',
                      'name' => 'url',
                      'type' => 'url',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                    ),
                  ),
                ),
                array(
                  'key' => 'field_5e1cfb4ccc899',
                  'label' => 'Enabled',
                  'name' => 'section-enabled',
                  'type' => 'clone',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'clone' => array(
                    0 => 'field_5e1cfb22cc898',
                  ),
                  'display' => 'seamless',
                  'layout' => 'block',
                  'prefix_label' => 0,
                  'prefix_name' => 0,
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            'layout_5e1e39a375a4b' => array(
              'key' => 'layout_5e1e39a375a4b',
              'name' => 'brand-grid',
              'label' => 'Brand Grid',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5e1e39af75a4c',
                  'label' => 'Section title',
                  'name' => 'section-title',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                ),
                array(
                  'key' => 'field_5e1e39c175a4d',
                  'label' => 'Section body',
                  'name' => 'section-body',
                  'type' => 'textarea',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => 3,
                  'new_lines' => 'wpautop',
                ),
                array(
                  'key' => 'field_5e1e39fc75a4f',
                  'label' => 'Brands',
                  'name' => 'brands',
                  'type' => 'repeater',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'collapsed' => 'field_5e1e3a0d75a50',
                  'min' => 0,
                  'max' => 0,
                  'layout' => 'table',
                  'button_label' => 'Add Brand',
                  'sub_fields' => array(
                    array(
                      'key' => 'field_5e1e3a0d75a50',
                      'label' => 'Name',
                      'name' => 'brand-name',
                      'type' => 'text',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                    ),
                    array(
                      'key' => 'field_5e1e3a1d75a51',
                      'label' => 'Description',
                      'name' => 'brand-description',
                      'type' => 'textarea',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'maxlength' => 500,
                      'rows' => 3,
                      'new_lines' => 'wpautop',
                    ),
                    array(
                      'key' => 'field_5e1e3a4075a52',
                      'label' => 'Image',
                      'name' => 'brand-image',
                      'type' => 'image',
                      'instructions' => 'Image should be square',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'return_format' => 'array',
                      'preview_size' => 'medium',
                      'library' => 'all',
                      'min_width' => '',
                      'min_height' => '',
                      'min_size' => '',
                      'max_width' => '',
                      'max_height' => '',
                      'max_size' => '',
                      'mime_types' => '',
                    ),
                    array(
                      'key' => 'field_5e1e3a4c75a53',
                      'label' => 'Logo',
                      'name' => 'brand-logo',
                      'type' => 'select',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'choices' => array(
                        'ace' => 'Ace',
                        'bioionic' => 'Bio Ionic',
                        'epic-pro' => 'Epic Pro',
                        'goody' => 'Goody',
                        'ouidad' => 'Ouidad',
                        'solano' => 'Solano',
                        'twist' => 'Twist',
                        'wetbrush' => 'WetBrush',
                      ),
                      'default_value' => array(
                      ),
                      'allow_null' => 0,
                      'multiple' => 0,
                      'ui' => 0,
                      'return_format' => 'value',
                      'ajax' => 0,
                      'placeholder' => '',
                    ),
                    array(
                      'key' => 'field_5e2fecdd6cdbf',
                      'label' => 'URL',
                      'name' => 'brand-url',
                      'type' => 'url',
                      'instructions' => 'Add a URL to link the image',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                    ),
                  ),
                ),
                array(
                  'key' => 'field_5e1e39d775a4e',
                  'label' => 'Enabled',
                  'name' => 'section-enabled',
                  'type' => 'clone',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'clone' => array(
                    0 => 'field_5e1cfb22cc898',
                  ),
                  'display' => 'seamless',
                  'layout' => 'block',
                  'prefix_label' => 0,
                  'prefix_name' => 0,
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            'layout_5e1eb27b54ab8' => array(
              'key' => 'layout_5e1eb27b54ab8',
              'name' => 'quotes',
              'label' => 'Quotes',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5e1eb2b954abb',
                  'label' => 'Play as slideshow',
                  'name' => 'quotes-slideshow',
                  'type' => 'true_false',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'message' => '',
                  'default_value' => 0,
                  'ui' => 1,
                  'ui_on_text' => '',
                  'ui_off_text' => '',
                ),
                array(
                  'key' => 'field_5e1eb2a154aba',
                  'label' => 'Quotes',
                  'name' => 'quotes',
                  'type' => 'repeater',
                  'instructions' => 'If you want quotation marks around the quotes you need to include them in the quote text.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'collapsed' => 'field_5e1eb2ed54abc',
                  'min' => 0,
                  'max' => 0,
                  'layout' => 'block',
                  'button_label' => 'Add Quote',
                  'sub_fields' => array(
                    array(
                      'key' => 'field_5e1eb2ed54abc',
                      'label' => 'Brand name',
                      'name' => 'brand-name',
                      'type' => 'text',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                    ),
                    array(
                      'key' => 'field_5e1eb2fd54abd',
                      'label' => 'Logo',
                      'name' => 'brand-logo',
                      'type' => 'select',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                      ),
                      'choices' => array(
                        'ace' => 'Ace',
                        'bioionic' => 'Bio Ionic',
                        'epic-pro' => 'Epic Pro',
                        'goody' => 'Goody',
                        'ouidad' => 'Ouidad',
                        'solano' => 'Solano',
                        'twist' => 'Twist',
                        'wetbrush' => 'WetBrush',
                      ),
                      'default_value' => array(
                      ),
                      'allow_null' => 0,
                      'multiple' => 0,
                      'ui' => 0,
                      'return_format' => 'value',
                      'ajax' => 0,
                      'placeholder' => '',
                    ),
                    array(
                      'key' => 'field_5e1eb32e54abe',
                      'label' => 'Quote',
                      'name' => 'quote',
                      'type' => 'textarea',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'maxlength' => '',
                      'rows' => 3,
                      'new_lines' => 'wpautop',
                    ),
                    array(
                      'key' => 'field_5e212612799e7',
                      'label' => 'By',
                      'name' => 'quote-by',
                      'type' => 'text',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                    ),
                  ),
                ),
                array(
                  'key' => 'field_5e1eb28954ab9',
                  'label' => 'Enabled',
                  'name' => 'section-enabled',
                  'type' => 'clone',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'clone' => array(
                    0 => 'field_5e1cfb22cc898',
                  ),
                  'display' => 'seamless',
                  'layout' => 'block',
                  'prefix_label' => 0,
                  'prefix_name' => 0,
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            'layout_5e1ec388e8d72' => array(
              'key' => 'layout_5e1ec388e8d72',
              'name' => 'feature',
              'label' => 'Feature',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5e1ec3a8e8d73',
                  'label' => 'Title',
                  'name' => 'feature-title',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                ),
                array(
                  'key' => 'field_5e1ec3bbe8d74',
                  'label' => 'Body',
                  'name' => 'feature-body',
                  'type' => 'wysiwyg',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'tabs' => 'all',
                  'toolbar' => 'basic',
                  'media_upload' => 0,
                  'delay' => 0,
                ),
                array(
                  'key' => 'field_5e1ec3e7e8d75',
                  'label' => 'Image',
                  'name' => 'feature-image',
                  'type' => 'image',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'return_format' => 'array',
                  'preview_size' => 'medium',
                  'library' => 'all',
                  'min_width' => '',
                  'min_height' => '',
                  'min_size' => '',
                  'max_width' => '',
                  'max_height' => '',
                  'max_size' => '',
                  'mime_types' => '',
                ),
                array(
                  'key' => 'field_5e1ec3f4e8d76',
                  'label' => 'Image position',
                  'name' => 'feature-position',
                  'type' => 'radio',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    'left' => 'Left',
                    'right' => 'Right',
                  ),
                  'allow_null' => 0,
                  'other_choice' => 0,
                  'default_value' => '',
                  'layout' => 'horizontal',
                  'return_format' => 'value',
                  'save_other_choice' => 0,
                ),
                array(
                  'key' => 'field_5e1ec64053c8d',
                  'label' => 'Enabled',
                  'name' => 'section-enabled',
                  'type' => 'clone',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'clone' => array(
                    0 => 'field_5e1cfb22cc898',
                  ),
                  'display' => 'seamless',
                  'layout' => 'block',
                  'prefix_label' => 0,
                  'prefix_name' => 0,
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            'layout_5e1eca0afdc00' => array(
              'key' => 'layout_5e1eca0afdc00',
              'name' => 'job-listing',
              'label' => 'Job listing',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5e1eca30fdc01',
                  'label' => 'Section title',
                  'name' => 'section-title',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                ),
                array(
                  'key' => 'field_5e1eca81249d0',
                  'label' => '',
                  'name' => '',
                  'type' => 'message',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'message' => 'This section uses data from the Jobs posts. Any published Jobs will appear in this section.',
                  'new_lines' => 'wpautop',
                  'esc_html' => 0,
                ),
                array(
                  'key' => 'field_5e1ece42dcc9b',
                  'label' => 'Enabled',
                  'name' => 'section-enabled',
                  'type' => 'clone',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'clone' => array(
                    0 => 'field_5e1cfb22cc898',
                  ),
                  'display' => 'seamless',
                  'layout' => 'block',
                  'prefix_label' => 0,
                  'prefix_name' => 0,
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            'layout_5e20b8429b77a' => array(
              'key' => 'layout_5e20b8429b77a',
              'name' => 'articles',
              'label' => 'Articles',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5e20b8429b77c',
                  'label' => '',
                  'name' => '',
                  'type' => 'message',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'message' => '<b>This section uses data from the Articles posts. Any published Articles will appear in this section.</b>',
                  'new_lines' => 'wpautop',
                  'esc_html' => 0,
                ),
                array(
                  'key' => 'field_5e20b8429b77b',
                  'label' => 'Featured articles title',
                  'name' => 'featured-title',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                ),
                array(
                  'key' => 'field_5e20d31c7ba2b',
                  'label' => 'Feature recent articles',
                  'name' => 'feature-latest',
                  'type' => 'number',
                  'instructions' => 'Number of most recent articles to show above the filter. Must be multiples of 2 or 0 for none.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => 2,
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'min' => 0,
                  'max' => 6,
                  'step' => 2,
                ),
                array(
                  'key' => 'field_5e20b899d4aec',
                  'label' => 'Filtered articles title',
                  'name' => 'filter-title',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                ),
                array(
                  'key' => 'field_5e20b8429b77d',
                  'label' => 'Enabled',
                  'name' => 'section-enabled',
                  'type' => 'clone',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'clone' => array(
                    0 => 'field_5e1cfb22cc898',
                  ),
                  'display' => 'seamless',
                  'layout' => 'block',
                  'prefix_label' => 0,
                  'prefix_name' => 0,
                ),
              ),
              'min' => '',
              'max' => '',
            ),
          ),
          'button_label' => 'Add Section',
          'min' => '',
          'max' => '',
        ),
        array(
          'key' => 'field_604945d897568',
          'label' => 'Popup',
          'name' => 'popup',
          'type' => 'group',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'layout' => 'block',
          'sub_fields' => array(
            array(
              'key' => 'field_6049462b9756a',
              'label' => 'Enabled',
              'name' => 'enabled',
              'type' => 'true_false',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'message' => '',
              'default_value' => 0,
              'ui' => 1,
              'ui_on_text' => '',
              'ui_off_text' => '',
            ),
            array(
              'key' => 'field_6049460a97569',
              'label' => 'Content',
              'name' => 'content',
              'type' => 'textarea',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'maxlength' => '',
              'rows' => '',
              'new_lines' => 'wpautop',
            ),
            array(
              'key' => 'field_604946419756b',
              'label' => 'Image',
              'name' => 'image',
              'type' => 'image',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'return_format' => 'array',
              'preview_size' => 'medium',
              'library' => 'all',
              'min_width' => '',
              'min_height' => '',
              'min_size' => '',
              'max_width' => '',
              'max_height' => '',
              'max_size' => '',
              'mime_types' => '',
            ),
            array(
              'key' => 'field_604947069037f',
              'label' => 'Identifier',
              'name' => 'identifier',
              'type' => 'text',
              'instructions' => 'If you change the content, change the identifier to something unique. This name will be used in the cookie.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => 'notice-2021-02-02',
              'prepend' => '',
              'append' => '',
              'maxlength' => 32,
            ),
          ),
        ),    
      ),
      'location' => array(
        array(
          array(
            'param' => 'post_type',
            'operator' => '==',
            'value' => 'page',
          ),
          array(
            'param' => 'page_template',
            'operator' => '==',
            'value' => 'page-sections.php',
          ),
        ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => array(
        0 => 'the_content',
        1 => 'featured_image',
        2 => 'categories',
        3 => 'tags',
      ),
      'active' => true,
      'description' => '',
    ));
    
    acf_add_local_field_group(array(
      'key' => 'group_5e1ecb39564ae',
      'title' => 'Job',
      'fields' => array(
        array(
          'key' => 'field_5e1ecb5c00473',
          'label' => 'Department',
          'name' => 'department',
          'type' => 'radio',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array(
            'Creative' => 'Creative',
            'Communications' => 'Communications',
            'Customer' => 'Customer',
            'Finance' => 'Finance',
            'Legal' => 'Legal',
            'Operations' => 'Operations',
            'Marketing' => 'Marketing',
          ),
          'allow_null' => 0,
          'other_choice' => 0,
          'default_value' => '',
          'layout' => 'horizontal',
          'return_format' => 'value',
          'save_other_choice' => 0,
        ),
        array(
          'key' => 'field_5e1ecbc000474',
          'label' => 'Location',
          'name' => 'location',
          'type' => 'radio',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array(
            'New York' => 'New York',
            'Long Island' => 'Long Island',
            'Atlanta' => 'Atlanta',
          ),
          'allow_null' => 0,
          'other_choice' => 0,
          'default_value' => '',
          'layout' => 'horizontal',
          'return_format' => 'value',
          'save_other_choice' => 0,
        ),
        array(
          'key' => 'field_5e1ecc0100475',
          'label' => 'LinkedIn url',
          'name' => 'url',
          'type' => 'url',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
        ),
      ),
      'location' => array(
        array(
          array(
            'param' => 'post_type',
            'operator' => '==',
            'value' => 'job',
          ),
        ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => array(
        0 => 'the_content',
        1 => 'format',
        2 => 'page_attributes',
        3 => 'featured_image',
        4 => 'categories',
        5 => 'tags',
      ),
      'active' => true,
      'description' => '',
    ));
    
    endif;
?>